global:
  ingress:
    enabled: true
    hostname: "blah.foo.com"
    ingressClassName: ""


modules:
  - access-control:
      path: /authz(/|$)(.*) 
      servicePort: 9006
      annotations: {}
  - gateway:
      path: /gateway(/|$)(.*) 
      servicePort: 20023
      annotations: {}
